name: Generate and Deploy Graphviz SVG

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Graphviz
        run: sudo apt-get install graphviz

      - name: Generate SVG
        run: dot -Tsvg ai_knowledge_graph.dot -o ai_knowledge_graph.svg

      - name: Setup Pages
        uses: actions/setup-pages@v3

      - name: Deploy to GitHub Pages
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add ai_knowledge_graph.svg
          git add index.html
          git commit -m "Auto-generate SVG and deploy"
          git push
